language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

addons:
  postgresql: "9.6"

env:
  global:
    - LOGIDZE_DB_USER=postgres
    - LOGIDZE_DB_NAME=logidze

before_script:
  - gem update --system
  - bundle exec rake dummy:db:create
  - psql -U postgres -d logidze -c 'CREATE EXTENSION IF NOT EXISTS hstore;'
  - RAILS_ENV=test bundle exec rake dummy:db:create dummy:db:migrate

matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.5
      gemfile: gemfiles/railsmaster.gemfile
